# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ dev/GruenbeckCloud ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/dsgrafiniert -Dtoken=ce7254447fac50a97970c9bc114b4189df4eeb0e --file bundles/org.openhab.binding.gruenbeckcloud/pom.xml
    
